#
# 이 파일은 도커를 관리하는 파일입니다. 
#
version: '2'
services:
    falinux-services-supercom-backend:
        build:
            context     : ./
            dockerfile  : Dockerfile
        image           : services/falinux-supercom-backend:latest

    falinux-services-supercom-backend-dev:
        build:
            context     : ./
            dockerfile  : Dockerfile
        image           : services/falinux-supercom-backend:latest
        volumes:
          - ${selected_directory}:/app
        ports:
          - 8000:8000
        working_dir: /app
        command: >
          bash -c 'uvicorn main:app --host 0.0.0.0 --port 8000 --reload'